module.exports = {
    CREATE_WORKER: 'CREATE_WORKER',
    DELETE_WORKER: 'DELETE_WORKER',
    HIDE_CREATE_WORKER_MODAL: 'HIDE_CREATE_WORKER_MODAL',
    SHOW_CREATE_WORKER_MODAL: 'SHOW_CREATE_WORKER_MODAL'
};
