module.exports = {
    CREATE_WORKER: 'CREATE_WORKER',
    CREATE_SHIFT: 'CREATE_SHIFT',
    DELETE_WORKER: 'DELETE_WORKER',
    DELETE_SHIFT: 'DELETE_SHIFT',
    HIDE_CREATE_WORKER_MODAL: 'HIDE_CREATE_WORKER_MODAL',
    SHOW_CREATE_WORKER_MODAL: 'SHOW_CREATE_WORKER_MODAL',
    HIDE_CREATE_SHIFT_MODAL: 'HIDE_CREATE_SHIFT_MODAL',
    SHOW_CREATE_SHIFT_MODAL: 'SHOW_CREATE_SHIFT_MODAL',
    SHOW_DELETE_WORKER_MODAL: 'SHOW_DELETE_WORKER_MODAL',
    HIDE_DELETE_WORKER_MODAL: 'HIDE_DELETE_WORKER_MODAL',
    SHOW_DELETE_SHIFT_MODAL: 'SHOW_DELETE_SHIFT_MODAL',
    HIDE_DELETE_SHIFT_MODAL: 'HIDE_DELETE_SHIFT_MODAL',
    HIDE_LINK_SHIFT_MODAL: 'HIDE_LINK_SHIFT_MODAL',
    SHOW_LINK_SHIFT_MODAL: 'SHOW_LINK_SHIFT_MODAL',
    HIDE_DELETE_SHIFT_LINK_MODAL: 'HIDE_DELETE_SHIFT_LINK_MODAL',
    SHOW_DELETE_SHIFT_LINK_MODAL: 'SHOW_DELETE_SHIFT_LINK_MODAL',
    DELETE_SHIFT_LINK: 'DELETE_SHIFT_LINK'
};
