module.exports = {
    CREATE_WORKER: 'CREATE_WORKER',
    CREATE_SHIFT: 'CREATE_SHIFT',
    DELETE_WORKER: 'DELETE_WORKER',
    HIDE_CREATE_WORKER_MODAL: 'HIDE_CREATE_WORKER_MODAL',
    SHOW_CREATE_WORKER_MODAL: 'SHOW_CREATE_WORKER_MODAL',
    HIDE_CREATE_SHIFT_MODAL: 'HIDE_CREATE_SHIFT_MODAL',
    SHOW_CREATE_SHIFT_MODAL: 'SHOW_CREATE_SHIFT_MODAL'
};
